theme: jekyll-theme-architect
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Demo Buoi 1</title>
</head>
<body>
    <!-- ctrl + / de ghi chu -->
    <div>This is the first day with HTML5</div>
    <h1 style = "color: crimson;">This is H1</h1> <!-- chu co mau do-->
    <h2>This is H2</h2>
    <h3>This is H3</h3>
    <h4>This is H4</h4>
    <h5>This is H5</h5>
    <h6>This is H6</h6>
    <div><b>This is b</b></div> <!-- chu in dam-->
    <div><u>This is u</u></div> <!-- chu duoc gach chan-->
    <div><i>This is i</i></div> <!--chu in nghieng-->
    <div>
        <p>This is first line</p> <!-- chu binh thuong -->
        <p>This is second line</p>
    </div>
    <div>
        <small>This is third line</small> <!-- chu nho-->
        <del>This is fourth line</del> <!--chu bi gach di-->
        <ins>This is fifth line</ins> <!--tuong tu the u-->
        <strong>This is sixth line</strong> <!-- tuong tu the b-->
        <sup>This is seventh line</sup> <!-- chu nhu so luy thua-->
        <sub>This is eighth line</sub> <!-- chu mỏng va nho-->
        <br>This is nineth line<br>
    </div>
        <!-- <i>A Brief History of Time</i>
        <p>by Stephen Hawking has sold over ten million copies worldwide</p>
        <blockquote>
            <p>"When one door closes, another opens; but we often look so long and so regrefully upon the closed door that we do not see the one which has opened for us."-Alexander Gramham Bell</p>
        </blockquote>
            <div><sub>Are You Sleeping (Frère Jacques)</sub></div>
            <div><sub>Are you sleeping, are you sleeping?</sub></div>
            <div><sub>Brother John, Brother John?</sub></div>
            <div><sub>Morning bells are ringing, morning bells are ringing</sub></div>
           <div><sub>Ding ding dong, ding ding dong.</sub></div> --> <!-- bai ben con loi, sua lai sau -->
    <h2 style = "color: crimson;">Cach lam kem chay: </h2>
    <h3 style = "color: aqua;">Nguyen lieu: </h3>
    <!-- tao list -->
    <!---- ul duoc dung de cham dau dong, ol dung de dem so dau dong -->
    <ul style = "color: darkorange;">
        <li><i>3 long do trung ga</i></li>
        <li><i>260ml kem whipping</i></li>
        <li><i>40gr duong</i></li>
        <li><i>1/2 muong ca phe vanilla</i></li>
    </ul>
    <h3 style = "color: darkseagreen;">Cac buoc thuc hien: </h3>
    <ol style="color: violet;">
        <li><i>Cho kem whipping cung vani cho vao noi hoa tan. Sau do, bac len bep nau hoi nong la tat bep</i></li>
        <li><i>Long do trung va duong cho vao noi khuay tan</i></li>
        <li><i>Do tu tu kem nong vao khuay deu.</i></li>
        <li><i>Luoc qua ray cho min.</i></li>
        <li><i>Bay gio do hon hop nay vao chen. Dat cac chen vao khay co long sau. Roi do nuoc soi vao ngap 1/3 chen kem.</i></li>
        <li><i>Lo nuong lam nong 140-150 do C truoc 15 phut. Sau do cho kay kem vao nuong 30 phut, qua 30 phut rac 1 chut duong len mat banh, tiep tuc nuong 5-7 phut nua cho mat kem co mau dep la tat lo, lay khay kem ra.</i></li>
    </ol>
    <p style = "color: olivedrab;">Cho kem chay nguoi, hay cho cac chen kem vao ngan mat tu lanh 1-2 tieng cho kem lanh truoc khi dung moi ngon.</p>
    <div><strong><i>Chuc cac ban thanh cong voi cach lam kem chay la mieng cho ca nha thuong thuc!</i></strong></div>
    <p>&copy;</p> <!-- in dau copyright -->
</body>
</html>
